# Comparison Bagging vs. RF vs. Decision Tree

In [6]:
# Bootstrap aggregation
import warnings
import numpy as np 
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import seaborn

from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.ensemble import BaggingClassifier, BaggingRegressor
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split

import pandas as pd
from sklearn.model_selection import cross_val_score, StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score

In [22]:
df = pd.read_csv('telecom_churn.csv')
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,OH,107,415,No,Yes,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,NJ,137,415,No,No,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,OH,84,408,Yes,No,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,OK,75,415,Yes,No,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [23]:
df['International plan'] = df['International plan'].map({'Yes':1,'No': 0})
df['Voice mail plan'] = df['Voice mail plan'].map({'Yes': 1, 'No': 0})
df['Churn'] = df['Churn'].map({True:1, False:0})

### RandomForesrtClassifier
1. bootstrap: use True, prevent overfitting
2. criterion: gini/entropy, what method you use for selecting node 
3. max_feature: maximum number, you cannot split features more than this number
    (1). auto: max = sqrt(n_features)
    (2). sqrt: max = sqrt(n_features)
    (3). log2: max = log2(n_features)
    (4). None: max = n_features
4. min_samples_split: minimum number of samples should be on a node to split. (if samples on a node is less than min_samples_split, then it cannot split anymore)
5. min_samples_leaf: minimum number of samples should be on a leaf node. (if samples in the left leaf node <min_sample_leaf,then we should remove left leaf node.)
6. max_leaf_nodes: 
7. min_impurity_split: a threshold decide whether this node should be split
8. min_impurity_decrease: ??? what's difference with min_impurity_split
9. n_estimator: how many trees in the forest

In [36]:
y = df['Churn']
X = df.drop(['Churn','State'],axis=1)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
rfc = RandomForestClassifier(random_state=42, n_jobs=-1, oob_score=True)
results = cross_val_score(rfc, X,y, cv=skf)
print("CV accuracy score: {:.2f}%".format(results.mean()*100))

CV accuracy score: 94.12%

In [58]:
## fine tune parameters - max_depth 
trees_count = [5, 10, 15, 20, 30, 50, 75, 100]

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for trees in trees_count:
    rfc = RandomForestClassifier(n_estimators=trees, random_state=42, n_jobs=-1, oob_score=True)
    
    temp_cv_ac = []
    temp_test_ac = []
    for train_index, test_index in skf.split(X,y):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        rfc.fit(X_train, y_train)
        temp_cv_ac.append(rfc.score(X_train, y_train))
        temp_test_ac.append(rfc.score(X_test, y_test))

    print("Tree# %d cv accuracy: %f, test accuracy: %f" %(trees, np.mean(temp_cv_ac)*100, np.mean(temp_test_ac)*100))
    
    
    
#     temp_results = cross_val_score(rfc, X, y, cv=skf) same as above
#     print("Trees# %d accuracy: %f" %(trees, np.mean(temp_results)*100))

Tree# 5 cv accuracy: 99.047422, test accuracy: 93.729397
Tree# 10 cv accuracy: 99.279904, test accuracy: 94.119247
Tree# 15 cv accuracy: 99.752475, test accuracy: 94.779322
Tree# 20 cv accuracy: 99.797480, test accuracy: 94.779187
Tree# 30 cv accuracy: 99.872491, test accuracy: 94.989172
Tree# 50 cv accuracy: 99.939993, test accuracy: 95.199292
Tree# 75 cv accuracy: 99.992501, test accuracy: 95.439307
Tree# 100 cv accuracy: 100.000000, test accuracy: 95.439262

False
[ True  True  True ... False False False]
[ True  True False ... False False  True]
False
[False  True False ...  True  True  True]

In [57]:
skf.split(X)

TypeError: split() missing 1 required positional argument: 'y'

In [56]:
X.iloc[[1,2]]

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
1,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1
2,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0